### ISSUE TITLE
Hardware inventory to continue on BIOS configuration collection error

### ISSUE THREAD

**Issue by joelrebel** [metal-toolbox/alloy#92]
The Inventory data collection should not be aborted on a BIOS data collection failure,

The fix for this is pretty simple

This method logs a warning instead of an error,
https://github.com/metal-toolbox/alloy/blob/0860d9da803470c54b7ea07010a345e0ffe3d906/internal/collect/inband.go#L56

And here the map length is checked before attempting to publish BIOS data,
https://github.com/metal-toolbox/alloy/blob/main/internal/publish/serverservice.go#LL286C73-L286C73

**Comment by diogomatsubara** [comment]
Added PR https://github.com/metal-toolbox/alloy/pull/93 with a fix for this
